"""
Code Review Agent — Reviews code changes (git diff) using AI.
Finds bugs, security issues, performance problems, and best practice violations.

Usage in pipeline:
  python code_review_agent.py --diff changes.diff
  python code_review_agent.py --files "src/index.js,src/auth.js"
  python code_review_agent.py  # Auto-detects git diff

What it checks:
  1. Security vulnerabilities (SQL injection, XSS, hardcoded secrets)
  2. Bug patterns (null pointer, race conditions, memory leaks)
  3. Performance issues (N+1 queries, unnecessary loops, large payloads)
  4. Best practices (error handling, input validation, logging)
  5. Code smells (duplicate code, long functions, magic numbers)
"""

import argparse
import json
import os
import subprocess
import sys
from ai_provider import get_ai_response


def get_git_diff():
    """Get the git diff of recent changes"""
    try:
        # Get diff of last commit
        result = subprocess.run(
            ["git", "diff", "HEAD~1", "--", "*.js", "*.ts", "*.py", "*.go", "*.java", "*.cpp"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout[:5000]  # Limit to 5000 chars
        
        # Fallback: get staged changes
        result = subprocess.run(
            ["git", "diff", "--cached"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout[:5000]
        
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def read_diff_file(filepath):
    """Read diff from a file"""
    if not filepath or not os.path.exists(filepath):
        return None
    try:
        with open(filepath, "r") as f:
            return f.read()[:5000]
    except IOError:
        return None


def read_source_files(file_list):
    """Read source files for review"""
    content = ""
    for filepath in file_list.split(","):
        filepath = filepath.strip()
        if os.path.exists(filepath):
            try:
                with open(filepath, "r") as f:
                    file_content = f.read()[:3000]
                    content += f"\n--- FILE: {filepath} ---\n{file_content}\n"
            except IOError:
                continue
    return content if content else None


def review_code(code_content, review_type="diff"):
    """Send code to AI for review"""
    
    prompt = f"""You are a senior code reviewer with expertise in security, performance, and best practices.
Review this code {'change (diff)' if review_type == 'diff' else 'and find issues'}.

## Code to Review:
```
{code_content[:4000]}
```

Provide a code review with:

1. **SECURITY ISSUES** (Critical — fix before merge)
   - SQL injection, XSS, SSRF, hardcoded secrets, auth bypass
   
2. **BUGS** (High — likely to cause errors)
   - Null pointer, unhandled exceptions, race conditions, logic errors

3. **PERFORMANCE** (Medium — will slow things down)
   - N+1 queries, unnecessary loops, missing pagination, large memory usage

4. **BEST PRACTICES** (Low — code quality improvements)
   - Error handling, input validation, naming, documentation

5. **OVERALL SCORE**: 1-10 (10 = perfect code)

6. **VERDICT**: APPROVE ✅ / REQUEST CHANGES 🔄 / BLOCK ❌

Format: Use bullet points. Be specific — include line references and fix suggestions.
If no issues found, say "Code looks good! ✅" """

    print("=" * 60)
    print("  🔍 AI CODE REVIEW AGENT — ANALYSIS")
    print("=" * 60)
    print()
    
    response = get_ai_response(prompt)
    print(response)
    
    print()
    print("=" * 60)
    print("  Review generated by AI Code Review Agent")
    print("=" * 60)
    
    return response


def main():
    parser = argparse.ArgumentParser(description="AI Code Review Agent")
    parser.add_argument("--diff", help="Path to diff file", default="")
    parser.add_argument("--files", help="Comma-separated list of files to review", default="")
    args = parser.parse_args()

    print("🔍 Code Review Agent starting...")
    print()

    code_content = None
    review_type = "diff"

    # Priority: diff file > source files > git diff
    if args.diff:
        code_content = read_diff_file(args.diff)
        review_type = "diff"
        print(f"  Reading diff from: {args.diff}")
    elif args.files:
        code_content = read_source_files(args.files)
        review_type = "files"
        print(f"  Reviewing files: {args.files}")
    else:
        code_content = get_git_diff()
        review_type = "diff"
        print("  Auto-detecting git diff...")

    if not code_content:
        print("⚠️  No code changes found to review.")
        print("  Provide --diff <file> or --files <file1,file2>")
        return

    print(f"  Code size: {len(code_content)} characters")
    print()

    review_code(code_content, review_type)


if __name__ == "__main__":
    main()
