"""
Log Analysis Agent — Analyzes pipeline/application logs to find errors,
performance issues, and anomalies.

Usage in pipeline:
  python log_analysis_agent.py --logs pipeline.log
  python log_analysis_agent.py --logs /var/log/app.log --type application

What it does:
  1. Reads log files (pipeline logs, app logs, error logs)
  2. Identifies errors, warnings, and anomalies
  3. Groups similar errors together
  4. Provides root cause analysis
  5. Suggests fixes for common errors
"""

import argparse
import json
import os
import sys
from ai_provider import get_ai_response


def read_log_file(filepath, tail_lines=100):
    """Read last N lines of a log file"""
    if not filepath or not os.path.exists(filepath):
        return None
    try:
        with open(filepath, "r") as f:
            lines = f.readlines()
            # Get last N lines
            recent_lines = lines[-tail_lines:] if len(lines) > tail_lines else lines
            return "".join(recent_lines)
    except IOError:
        return None


def analyze_logs(log_content, log_type="pipeline"):
    """Send logs to AI for analysis"""
    
    prompt = f"""You are a DevOps log analysis expert. Analyze these {log_type} logs and identify issues.

## Logs ({log_type}):
```
{log_content[:4000]}
```

Provide analysis:

1. **ERRORS FOUND** (list each unique error with count)
   - Error message
   - Likely cause
   - Fix suggestion

2. **WARNINGS** (potential issues)
   - Warning message
   - What could go wrong

3. **PERFORMANCE OBSERVATIONS**
   - Slow operations (anything > 5 seconds)
   - Resource usage patterns
   - Bottlenecks

4. **ANOMALIES** (unusual patterns)
   - Unexpected behavior
   - Suspicious activity

5. **ROOT CAUSE** (most likely reason for failures, if any)

6. **RECOMMENDED ACTIONS** (prioritized list)

Be concise. Focus on actionable findings. If logs look clean, say "No issues found ✅" """

    print("=" * 60)
    print("  📋 AI LOG ANALYSIS AGENT — FINDINGS")
    print("=" * 60)
    print()
    print(f"  Log type: {log_type}")
    print(f"  Lines analyzed: {log_content.count(chr(10))}")
    print()
    
    response = get_ai_response(prompt)
    print(response)
    
    print()
    print("=" * 60)
    print("  Analysis generated by AI Log Agent")
    print("=" * 60)
    
    return response


def main():
    parser = argparse.ArgumentParser(description="AI Log Analysis Agent")
    parser.add_argument("--logs", help="Path to log file", required=True)
    parser.add_argument("--type", default="pipeline", 
                       choices=["pipeline", "application", "error", "access", "system"])
    parser.add_argument("--lines", type=int, default=100, help="Number of recent lines to analyze")
    args = parser.parse_args()

    print("📋 Log Analysis Agent starting...")
    print(f"  Log file: {args.logs}")
    print(f"  Type: {args.type}")
    print(f"  Lines: {args.lines}")
    print()

    log_content = read_log_file(args.logs, args.lines)

    if not log_content:
        print(f"⚠️  Log file not found or empty: {args.logs}")
        return

    analyze_logs(log_content, args.type)


if __name__ == "__main__":
    main()
